In [14]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(10)

In [3]:
excel = pd.ExcelFile('../data.xls')
df = excel.parse("data")

print(df.shape)

(16383, 10)


In [4]:
X = df.iloc[:, 1:6].values
Y = df.iloc[:, 6:].values

print(X)
print(Y)

[['NMR' 1 8 3 8]
 ['NMR' 4 1 8 7]
 ['NMR' 3 4 7 6]
 ...
 ['NMR' 0 5 7 8]
 ['NMR' 5 1 6 8]
 ['NMR' 7 2 4 7]]
[[ 1 10  2  7]
 [ 3  1 10  6]
 [ 3  3  9  5]
 ...
 [ 0  4  6 10]
 [ 4  1  5 10]
 [ 9  2  3  6]]


In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

X[:, 0] = LabelEncoder().fit_transform(X[:, 0])
X = ColumnTransformer([("Weather", OneHotEncoder(), [0])], remainder = 'passthrough', ).fit_transform(X)

print(X.shape)

(16383, 9)


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

print(len(X_train))
print(len(X_test))

13106
3277


In [7]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(9, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(4))

model.compile(loss='mean_squared_error', metrics=['mean_absolute_error'], optimizer='adam')

Using TensorFlow backend.


In [8]:
model.fit(X_train, Y_train, epochs=100, batch_size=32, shuffle='batch')

Epoch 1/100
13106/13106 [==============================] - 1s 88us/step - loss: 4.3445 - mean_absolute_error: 1.4351
Epoch 2/100
13106/13106 [==============================] - 1s 51us/step - loss: 1.6147 - mean_absolute_error: 0.8121
Epoch 3/100
13106/13106 [==============================] - 1s 48us/step - loss: 0.8000 - mean_absolute_error: 0.6009
Epoch 4/100
13106/13106 [==============================] - 1s 55us/step - loss: 0.4045 - mean_absolute_error: 0.4652
Epoch 5/100
13106/13106 [==============================] - 1s 56us/step - loss: 0.2949 - mean_absolute_error: 0.4061
Epoch 6/100
13106/13106 [==============================] - 1s 53us/step - loss: 0.2476 - mean_absolute_error: 0.3748
Epoch 7/100
13106/13106 [==============================] - 1s 62us/step - loss: 0.2141 - mean_absolute_error: 0.3488
Epoch 8/100
13106/13106 [==============================] - 1s 61us/step - loss: 0.1842 - mean_absolute_error: 0.3231
Epoch 9/100
13106/13106 [==============================] - 1s 65

13106/13106 [==============================] - 1s 44us/step - loss: 0.0070 - mean_absolute_error: 0.0640
Epoch 70/100
13106/13106 [==============================] - 1s 42us/step - loss: 0.0068 - mean_absolute_error: 0.0630
Epoch 71/100
13106/13106 [==============================] - 1s 44us/step - loss: 0.0068 - mean_absolute_error: 0.0630
Epoch 72/100
13106/13106 [==============================] - 1s 43us/step - loss: 0.0060 - mean_absolute_error: 0.0591
Epoch 73/100
13106/13106 [==============================] - 1s 43us/step - loss: 0.0063 - mean_absolute_error: 0.0609
Epoch 74/100
13106/13106 [==============================] - 1s 42us/step - loss: 0.0060 - mean_absolute_error: 0.0587
Epoch 75/100
13106/13106 [==============================] - 1s 42us/step - loss: 0.0070 - mean_absolute_error: 0.0643
Epoch 76/100
13106/13106 [==============================] - 1s 43us/step - loss: 0.0057 - mean_absolute_error: 0.0577
Epoch 77/100
13106/13106 [==============================] - 1s 45us/s

In [9]:
print('Loss ', model.evaluate(X_test, Y_test))

3277/3277 [==============================] - 0s 46us/step
Loss  [0.0032870552178158523, 0.044669922441244125]


In [12]:
predictions = np.round(model.predict(X_test))

correct = 0
for i,j in zip(predictions, Y_test):
    if(np.array_equal(i, j)):
        correct += 1

total = len(predictions)
print('Total ', total)
print('Correct ', correct)
print('Accuracy:' , correct/total)

Total  3277
Correct  3277
Accuracy: 1.0


In [13]:
model.save('neural_network.h5')