In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(10)

In [3]:
excel = pd.ExcelFile('../data.xls')
df = excel.parse("data")

print(df.shape)

(16383, 10)


In [4]:
X = df.iloc[:, 1:6].values
Y = df.iloc[:, 6:].values

print(X)
print(Y)

[['NMR' 1 8 3 8]
 ['NMR' 4 1 8 7]
 ['NMR' 3 4 7 6]
 ...
 ['NMR' 0 5 7 8]
 ['NMR' 5 1 6 8]
 ['NMR' 7 2 4 7]]
[[ 1 10  2  7]
 [ 3  1 10  6]
 [ 3  3  9  5]
 ...
 [ 0  4  6 10]
 [ 4  1  5 10]
 [ 9  2  3  6]]


In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

X[:, 0] = LabelEncoder().fit_transform(X[:, 0])
X = OneHotEncoder(categorical_features = [0]).fit_transform(X).toarray()

print(X.shape)

(16383, 9)


/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:414: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:450: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

print(len(X_train))
print(len(X_test))

13106
3277


In [7]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(9, input_dim=9, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(4, activation='relu'))

model.compile(loss='mean_squared_error', optimizer='adam')

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.


In [8]:
model.fit(X_train, Y_train, epochs=100, batch_size=20, shuffle='batch')

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
13106/13106 [==============================] - 3s 224us/step - loss: 5.6809
Epoch 2/100
13106/13106 [==============================] - 2s 165us/step - loss: 1.0547
Epoch 3/100
13106/13106 [==============================] - 1s 102us/step - loss: 0.4419
Epoch 4/100
13106/13106 [==============================] - 1s 96us/step - loss: 0.2861
Epoch 5/100
13106/13106 [==============================] - 1s 97us/step - loss: 0.2186
Epoch 6/100
13106/13106 [==============================] - 1s 88us/step - loss: 0.1781
Epoch 7/100
13106/13106 [==============================] - 1s 94us/step - loss: 0.1442
Epoch 8/100
13106/13106 [==============================] - 1s 88us/step - loss: 0.1185
Epoch 9/100
13106/13106 [==============================] - 2s 132us/step - loss: 0.0991
Epoch 10/100
13106/13106 [==============================] - 1s 103us/step - loss: 0.0876
Epoch 11/100
13106/13106 [==============================] - 1s 88us/step - l

13106/13106 [==============================] - 1s 99us/step - loss: 0.0092
Epoch 91/100
13106/13106 [==============================] - 1s 105us/step - loss: 0.0041
Epoch 92/100
13106/13106 [==============================] - 1s 92us/step - loss: 0.0043
Epoch 93/100
13106/13106 [==============================] - 1s 91us/step - loss: 0.0056
Epoch 94/100
13106/13106 [==============================] - 1s 93us/step - loss: 0.0044
Epoch 95/100
13106/13106 [==============================] - 1s 91us/step - loss: 0.0050
Epoch 96/100
13106/13106 [==============================] - 1s 95us/step - loss: 0.0053
Epoch 97/100
13106/13106 [==============================] - 1s 94us/step - loss: 0.0052
Epoch 98/100
13106/13106 [==============================] - 1s 94us/step - loss: 0.0052
Epoch 99/100
13106/13106 [==============================] - 1s 110us/step - loss: 0.0045
Epoch 100/100
13106/13106 [==============================] - 1s 101us/step - loss: 0.0047


In [9]:
print('Loss ', model.evaluate(X_test, Y_test))

3277/3277 [==============================] - 0s 35us/step
Loss  0.0038725604117172438


In [10]:
predictions = np.round(model.predict(X_test))

correct = 0
for i,j in zip(predictions, Y_test):
    if(np.array_equal(i, j)):
        correct += 1

total = len(predictions)
print('Total ', total)
print('Correct ', correct)
print('Accuracy:' , correct/total)

Total  3277
Correct  3277
Accuracy: 1.0


In [11]:
# Best 0.026385646460644348 100% / 9 50 20 10 4
model.save('neural_network.h5')

In [12]:
from keras.models import load_model
model2 = load_model('neural_network.h5')

print('Loss2 ', model2.evaluate(X, Y))

16383/16383 [==============================] - 0s 29us/step
Loss2  0.003730430970023466
