In [21]:
import numpy as np
import pandas as pd

In [22]:
np.random.seed(10)

In [23]:
excel = pd.ExcelFile('../data.xls')
df = excel.parse("data")

print(df.shape)

(16383, 10)


In [24]:
X = df.iloc[:, 1:6].values
Y = df.iloc[:, 6:].values

print(X)
print(Y)

[['NMR' 1 8 3 8]
 ['NMR' 4 1 8 7]
 ['NMR' 3 4 7 6]
 ...
 ['NMR' 0 5 7 8]
 ['NMR' 5 1 6 8]
 ['NMR' 7 2 4 7]]
[[ 1 10  2  7]
 [ 3  1 10  6]
 [ 3  3  9  5]
 ...
 [ 0  4  6 10]
 [ 4  1  5 10]
 [ 9  2  3  6]]


In [25]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

X[:, 0] = LabelEncoder().fit_transform(X[:, 0])
X = OneHotEncoder(categorical_features = [0]).fit_transform(X).toarray()

print(X.shape)

(16383, 9)


/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

print(len(X_train))
print(len(X_test))

13106
3277


In [27]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(9, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(4))

model.compile(loss='mean_squared_error', metrics=['mean_absolute_error'], optimizer='adam')

In [28]:
model.fit(X_train, Y_train, epochs=100, batch_size=32, shuffle='batch')

Epoch 1/100
13106/13106 [==============================] - 1s 91us/step - loss: 4.3920 - mean_absolute_error: 1.4458
Epoch 2/100
13106/13106 [==============================] - 1s 52us/step - loss: 1.6363 - mean_absolute_error: 0.8198
Epoch 3/100
13106/13106 [==============================] - 1s 51us/step - loss: 0.8202 - mean_absolute_error: 0.6088
Epoch 4/100
13106/13106 [==============================] - 1s 87us/step - loss: 0.4161 - mean_absolute_error: 0.4723
Epoch 5/100
13106/13106 [==============================] - 1s 48us/step - loss: 0.2867 - mean_absolute_error: 0.4023
Epoch 6/100
13106/13106 [==============================] - 1s 48us/step - loss: 0.2380 - mean_absolute_error: 0.3680
Epoch 7/100
13106/13106 [==============================] - 1s 48us/step - loss: 0.2048 - mean_absolute_error: 0.3421
Epoch 8/100
13106/13106 [==============================] - 1s 68us/step - loss: 0.1785 - mean_absolute_error: 0.3197
Epoch 9/100
13106/13106 [==============================] - 1s 84

13106/13106 [==============================] - 1s 40us/step - loss: 0.0063 - mean_absolute_error: 0.0598
Epoch 70/100
13106/13106 [==============================] - 1s 49us/step - loss: 0.0059 - mean_absolute_error: 0.0577: 0s - loss: 0.0060 - mean_absolute_error: 
Epoch 71/100
13106/13106 [==============================] - 1s 70us/step - loss: 0.0063 - mean_absolute_error: 0.0598
Epoch 72/100
13106/13106 [==============================] - 1s 105us/step - loss: 0.0063 - mean_absolute_error: 0.0595
Epoch 73/100
13106/13106 [==============================] - 1s 62us/step - loss: 0.0053 - mean_absolute_error: 0.0548
Epoch 74/100
13106/13106 [==============================] - 1s 57us/step - loss: 0.0051 - mean_absolute_error: 0.0534
Epoch 75/100
13106/13106 [==============================] - 1s 63us/step - loss: 0.0054 - mean_absolute_error: 0.0552
Epoch 76/100
13106/13106 [==============================] - 1s 87us/step - loss: 0.0056 - mean_absolute_error: 0.0566
Epoch 77/100
13106/13106 

In [29]:
print('Loss ', model.evaluate(X_test, Y_test))

3277/3277 [==============================] - 0s 45us/step
Loss  [0.0035301967325620637, 0.046351663924032935]


In [30]:
predictions = np.round(model.predict(X_test))

correct = 0
for i,j in zip(predictions, Y_test):
    if(np.array_equal(i, j)):
        correct += 1

total = len(predictions)
print('Total ', total)
print('Correct ', correct)
print('Accuracy:' , correct/total)

Total  3277
Correct  3277
Accuracy: 1.0


In [31]:
model.save('neural_network.h5')